<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apizr" />
    <PackageReference Include="Fody">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ConfigureAwait.Fody">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="WTorricos.Results" />
  </ItemGroup>

  <ItemGroup>
    <None Update="**/FodyWeavers.*" Visible="false" />
    <None Update="**/.refitter*" Visible="false" />
  </ItemGroup>

</Project>